version: '3'

services:
  client:
    build: ./app
    command: uvicorn client.main:app --reload --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    networks:
      - my_network


  admin:
    build: ./app
    command: uvicorn admin.main:app --reload --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    networks:
      - my_network


  auth:
    build: ./app
    command: uvicorn auth.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - my_network

  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    networks:
      - my_network


  redis:
    build: ./redis
    networks:
      - my_network
      
networks:
  my_network: